export const MOCK_PROFILES = [
  {
    id: "1",
    name: "Ananya",
    age: 26,
    job: "Product Designer",
    image: require("@/assets/images/irina_dhruv.jpg"),
    location: "Mumbai, India",
    religion: "Hindu",
    height: "5'4\"",
    compatibility: 92,
    isVerified: true,
    bio: "I believe in meaningful conversations, family values, and growing together. Looking for someone who values tradition but has a modern outlook.",
    education: "B.Des from NIFT",
    kundaliMatch: "Gun Milan: 28/36",
    lifestyle: "Vegetarian, Non-Smoker",
    city: "Mumbai",
    images: [
      require("@/assets/images/irina_dhruv.jpg"),
      // In real app these would be different images
      require("@/assets/images/irina_dhruv.jpg"),
      require("@/assets/images/irina_dhruv.jpg"),
    ],
  },
  {
    id: "2",
    name: "Priya",
    age: 25,
    job: "Doctor (MD)",
    image: require("@/assets/images/doctor_profile.jpg"),
    location: "Delhi, India",
    religion: "Hindu",
    height: "5'6\"",
    compatibility: 88,
    isVerified: true,
    bio: "Passionate about medicine and helping others. In my free time, I love reading and traveling.",
    education: "MBBS, MD",
    kundaliMatch: "Gun Milan: 31/36",
    lifestyle: "Eggetarian",
    city: "Delhi",
    images: [
      require("@/assets/images/doctor_profile.jpg"),
      require("@/assets/images/doctor_profile.jpg"),
    ],
  },
  {
    id: "3",
    name: "Neha",
    age: 24,
    job: "Architect",
    image: require("@/assets/images/architect_profile.jpg"),
    location: "Bangalore, India",
    religion: "Hindu/Punjabi",
    height: "5'5\"",
    compatibility: 85,
    isVerified: false,
    bio: "Creative soul with a love for design and spaces. Looking for a partner who is ambitious and kind.",
    education: "B.Arch",
    kundaliMatch: "Not Matched",
    lifestyle: "Non-Vegetarian",
    city: "Bangalore",
    images: [
      require("@/assets/images/architect_profile.jpg"),
      require("@/assets/images/architect_profile.jpg"),
    ],
  },
];
