
    create table castes (
        active boolean not null,
        community_id bigint not null,
        id bigint generated by default as identity,
        caste_name varchar(255) not null,
        primary key (id)
    );

    create table chat_messages (
        deleted boolean not null,
        delivered boolean not null,
        seen boolean not null,
        visible_to_vendor boolean not null,
        id bigint generated by default as identity,
        receiver_id bigint,
        seen_at timestamp(6),
        sender_id bigint,
        sent_at timestamp(6),
        content varchar(2000),
        message varchar(2000),
        image_url varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table communities (
        active boolean not null,
        id bigint generated by default as identity,
        religion_id bigint not null,
        community_name varchar(255) not null,
        primary key (id)
    );

    create table explore_history (
        id bigint generated by default as identity,
        user_id bigint,
        viewed_at timestamp(6),
        viewed_user_id bigint,
        primary key (id)
    );

    create table gotras (
        active boolean not null,
        caste_id bigint not null,
        id bigint generated by default as identity,
        gotra_name varchar(255) not null,
        primary key (id)
    );

    create table otp_verification (
        attempt_count integer not null,
        is_used boolean not null,
        resend_count integer not null,
        expiry_time timestamp(6) not null,
        last_sent_at timestamp(6),
        otp_id bigint generated by default as identity,
        user_id bigint not null,
        otp_code varchar(255) not null,
        primary key (otp_id)
    );

    create table profile_photos (
        photo_order integer,
        id bigint generated by default as identity,
        profile_id bigint,
        photo_url varchar(255),
        type varchar(255) check (type in ('MAIN','EXTRA')),
        primary key (id)
    );

    create table religions (
        active boolean not null,
        id bigint generated by default as identity,
        religion_name varchar(255) not null,
        primary key (id)
    );

    create table service_request (
        accepted_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        service_id bigint,
        user_id bigint,
        vendor_id bigint,
        message varchar(500),
        status varchar(255) check (status in ('PENDING','ACCEPTED','REJECTED','CANCELLED')),
        primary key (id)
    );

    create table support_tickets (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        message varchar(5000),
        priority varchar(255) check (priority in ('LOW','MEDIUM','HIGH')),
        status varchar(255) check (status in ('OPEN','IN_PROGRESS','CLOSED')),
        subject varchar(255),
        primary key (id)
    );

    create table support_attachment (
        id bigint generated by default as identity,
        message_id bigint,
        ticket_id bigint,
        file_name varchar(255),
        file_type varchar(255),
        file_url varchar(255),
        primary key (id)
    );

    create table support_ticket_message (
        admin_message boolean not null,
        id bigint generated by default as identity,
        sender_id bigint,
        sent_at timestamp(6),
        ticket_id bigint,
        message varchar(5000),
        primary key (id)
    );

    create table user_profiles (
        brothers integer,
        date_of_birth date,
        height numeric(38,2),
        latitude float(53),
        longitude float(53),
        sisters integer,
        weight numeric(38,2),
        id bigint generated by default as identity,
        user_id bigint not null unique,
        about_me TEXT,
        annual_income varchar(255) check (annual_income in ('BELOW_2_LAKH','BETWEEN_2_TO_5_LAKH','BETWEEN_5_TO_10_LAKH','BETWEEN_10_TO_20_LAKH','BETWEEN_20_TO_50_LAKH','ABOVE_50_LAKH')),
        caste varchar(255),
        city varchar(255),
        community varchar(255),
        diet_preference varchar(255) check (diet_preference in ('VEGAN','JAIN','NOT_SPECIFIED')),
        drinking_habit varchar(255) check (drinking_habit in ('YES','NO','OCCASIONALLY')),
        eating_habit varchar(255) check (eating_habit in ('VEGETARIAN','NON_VEGETARIAN','EGGETARIAN','VEGAN','JAIN')),
        education varchar(255) check (education in ('HIGH_SCHOOL','BACHELORS','MASTERS','PHD','OTHER')),
        employment_type varchar(255) check (employment_type in ('FULL_TIME','PART_TIME','FREELANCING','CONTRACT')),
        family_status varchar(255) check (family_status in ('UPPER_CLASS','MIDDLE_CLASS','LOWER_CLASS')),
        family_type varchar(255) check (family_type in ('JOINT_FAMILY','NUCLEAR_FAMILY')),
        family_values varchar(255) check (family_values in ('TRADITIONAL','MODERN','LIBERAL')),
        father_name varchar(255),
        father_occupation varchar(255) check (father_occupation in ('GOVERNMENT_SERVICE','PRIVATE_SECTOR','CIVIL_SERVICE','BUSINESS','DEFENSE','RETIRED','FARMER','NOT_WORKING','OTHER')),
        gender varchar(255) check (gender in ('MALE','FEMALE')),
        gotra varchar(255),
        health_note varchar(255),
        manglik_status varchar(255) check (manglik_status in ('YES','NO')),
        mother_name varchar(255),
        mother_occupation varchar(255) check (mother_occupation in ('GOVERNMENT_SERVICE','PRIVATE_SECTOR','CIVIL_SERVICE','BUSINESS','DEFENSE','RETIRED','FARMER','NOT_WORKING','OTHER')),
        nakshatra varchar(255) check (nakshatra in ('ASHWINI','BHARANI','KRITTIKA','ROHINI','MRIGASHIRSHA','ARDRA','PUNARVASU','PUSHYA','ASHLESHA','MAGHA','PURVA_PHALGUNI','UTTARA_PHALGUNI','HASTA','CHITRA','SWATI','VISHAKHA','ANURADHA','JYESHTHA','MULA','PURVA_ASHADHA','UTTARA_ASHADHA','SHRAVANA','DHANISHTA','SHATABHISHA','PURVA_BHADRAPADA','UTTARA_BHADRAPADA','REVATI')),
        occupation varchar(255) check (occupation in ('GOVERNMENT_SERVICE','PRIVATE_SECTOR','CIVIL_SERVICE','BUSINESS','DEFENSE','RETIRED','FARMER','NOT_WORKING','OTHER')),
        profile_created_by varchar(255) check (profile_created_by in ('SELF','PARENT','SIBLING','FRIEND','RELATIVE')),
        profile_photo_url varchar(255),
        rashi varchar(255) check (rashi in ('ARIES','TAURUS','GEMINI','CANCER','LEO','VIRGO','LIBRA','SCORPIO','SAGITTARIUS','CAPRICORN','AQUARIUS','PISCES')),
        religion varchar(255),
        smoking_habit varchar(255) check (smoking_habit in ('YES','NO','OCCASIONALLY')),
        sub_caste varchar(255),
        primary key (id)
    );

    create table user_relations (
        created_at timestamp(6),
        from_user_id bigint,
        id bigint generated by default as identity,
        to_user_id bigint,
        report_reason varchar(500),
        type varchar(255) check (type in ('SHORTLIST','LIKE','BLOCK','UNBLOCK','REPORT','UNREPORT','MATCH','REQUEST')),
        primary key (id)
    );

    create table user_settings (
        max_age integer,
        max_distance_km integer,
        min_age integer,
        notify_connection_accepted boolean not null,
        notify_connection_request boolean not null,
        notify_new_message boolean not null,
        photos_require_connection boolean not null,
        profile_visible boolean not null,
        show_distance boolean not null,
        show_last_seen boolean not null,
        show_online_status boolean not null,
        user_id bigint not null,
        primary key (user_id)
    );

    create table users (
        is_verified boolean,
        reset_token_expiry timestamp(6),
        user_id bigint generated by default as identity,
        auth_provider varchar(255),
        email varchar(255) unique,
        full_name varchar(255),
        password varchar(255),
        phone_number varchar(255) unique,
        profile_image_url varchar(255),
        reset_token varchar(255),
        primary key (user_id)
    );

    create table user_settings_communities (
        user_settings_user_id bigint not null,
        communities varchar(255)
    );

    create table user_settings_education_levels (
        user_settings_user_id bigint not null,
        education_levels varchar(255)
    );

    create table user_settings_lifestyle_preferences (
        user_settings_user_id bigint not null,
        lifestyle_preferences varchar(255)
    );

    create table user_settings_marital_status (
        user_settings_user_id bigint not null,
        marital_status varchar(255)
    );

    create table user_settings_professions (
        user_settings_user_id bigint not null,
        professions varchar(255)
    );

    create table user_settings_religions (
        user_settings_user_id bigint not null,
        religions varchar(255)
    );

    create table vendor_conversation (
        chat_enabled boolean not null,
        id bigint generated by default as identity,
        service_request_id bigint,
        user_id bigint,
        vendor_id bigint,
        type varchar(255) check (type in ('USER_USER','USER_VENDOR')),
        primary key (id)
    );

    alter table if exists castes 
       add constraint FKsm923g88m0foq1s1fj9nfxol1 
       foreign key (community_id) 
       references communities;

    alter table if exists communities 
       add constraint FK63ei3cd16esnj42ge2u1kx3hu 
       foreign key (religion_id) 
       references religions;

    alter table if exists gotras 
       add constraint FKqcpchw70hobijjgrc7v84vhua 
       foreign key (caste_id) 
       references castes;

    alter table if exists otp_verification 
       add constraint FKmtitrif16hpdkhtr4m4kgvfv8 
       foreign key (user_id) 
       references users;

    alter table if exists profile_photos 
       add constraint FK8cla5rrt8g1qcg5233o9kwqp4 
       foreign key (profile_id) 
       references user_profiles;

    alter table if exists user_profiles 
       add constraint FKjcad5nfve11khsnpwj1mv8frj 
       foreign key (user_id) 
       references users;

    alter table if exists user_settings_communities 
       add constraint FKcgcgmv1u7r5thgdme0lojtqv 
       foreign key (user_settings_user_id) 
       references user_settings;

    alter table if exists user_settings_education_levels 
       add constraint FKpf294dqb5vbn9oa32dd72ohvx 
       foreign key (user_settings_user_id) 
       references user_settings;

    alter table if exists user_settings_lifestyle_preferences 
       add constraint FKgibd2c8hckgmxil7fv1ec9r7w 
       foreign key (user_settings_user_id) 
       references user_settings;

    alter table if exists user_settings_marital_status 
       add constraint FK6isvhn6ulecsq1hsiptp1pvtb 
       foreign key (user_settings_user_id) 
       references user_settings;

    alter table if exists user_settings_professions 
       add constraint FKp5enltiw8ft5tai625777aik 
       foreign key (user_settings_user_id) 
       references user_settings;

    alter table if exists user_settings_religions 
       add constraint FK7ham252r4s0fxya8j06jt32a5 
       foreign key (user_settings_user_id) 
       references user_settings;

