# ===============================
# APPLICATION
# ===============================
spring.application.name=ShubhVivah
server.port=8085

# ===============================
# DATABASE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/shubhvivah_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# Debug logging for troubleshooting
logging.level.com.example.shubhvivah=DEBUG


jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcklkIjoxLCJpYXQiOjE3NzEzOTgxMzksImV4cCI6MTc3MTQ4NDUzOX0.Z1-nyjg3Vxqv8gdHhCU5PKZCKYFVnOXyyzzyz79oMZ4
jwt.expiration=86400000

# ===============================
# EMAIL (SMTP) - FOR OTP (FUTURE)
# ===============================
# ===============================
# EMAIL (SMTP) CONFIGURATION
# ===============================

spring.mail.host=smtpout.secureserver.net
spring.mail.port=587

spring.mail.username=support@shubhvivah.ltd
spring.mail.properties.mail.smtp.from=support@shubhvivah.ltd

spring.mail.password=Thynktech@2000

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp

app.reset-password.base-url=http://localhost:8085/reset-password

## ===============================
## LOGGING (OPTIONAL BUT GOOD)
## ===============================
#logging.level.org.springframework.web=INFO
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
cloudinary.cloud-name=dhn9yyv72
cloudinary.api-key=426564232229413
cloudinary.api-secret=eGtWYWjHAGJoBjLGg-2SGT1w5Xo
